### PR TITLE
make the config file configurable

### PR DESCRIPTION
**Pull request by fgksgf**

### CODE REVIEW

**Review by kezhenxu94 — APPROVED** [review]
Thanks!! 🙇🏻

**Comment by wu-sheng** [comment]
-c seems not in the doc.

**Comment by wu-sheng** [comment]
https://github.com/apache/skywalking-eyes#configurations This should be updated too.

**Comment by kezhenxu94** [comment]
> https://github.com/apache/skywalking-eyes#configurations This should be updated too.

The `configurations` section is all about the **contents** in config file `.licneserc.yaml`, and `-c` is a pointer to the config file itself.

> -c seems not in the doc.

It's in the doc, in example command
Screen Shot 2021-08-16 at 15 05 40

**Pull request merged**
