### PR TITLE
Add support for resolving npm dependencies' licenses

### PR DESCRIPTION
**Pull request by zooltd**
1. Parse the project package.json file to gather the required packages
2. Run command 'npm install' to install or update the required node packages (can skip)
3. Walk through each package's root directory to resolve licenses
    - STEP 1: Try to find and parse the package.json file to capture the license field
    - STEP 2: Try to find the license file to identify the license

### CODE REVIEW

**Comment by wu-sheng** [comment]
You should update the doc to show how to use this.

**Review by kezhenxu94 — COMMENTED** [review]
This is a very good start point to resolve dependencies’ licenses in NPM projects. 

This PR only resolves the direct dependencies’ licenses, will you continue to resolve their transitive dependencies in next PR?

**Comment by zooltd** [comment]
> This is a very good start point to resolve dependencies’ licenses in NPM projects.
> 
> This PR only resolves the direct dependencies’ licenses, will you continue to resolve their transitive dependencies in next PR?

Glad to take it. Also, I'm planning to resolve dev-dependencies' licenses.

**Comment by wu-sheng** [comment]
Notice, dev-dependency is not binary level or source code level dependency.
They mostly are considered as a convenient tools to enhance dev stage.
I could recommend to process transitive dependency. A.k.a, dependencies of dependencies. Those are true runtime dependencies too.

**Comment by wu-sheng** [comment]
Dev-tool should not include commercial or unknown licenses. But even GPL and AGPL are fine to use, that is what I mean different.

**Comment by zooltd** [comment]
> Notice, dev-dependency is not binary level or source code level dependency.
> They mostly are considered as a convenient tools to enhance dev stage.
> I could recommend to process transitive dependency. A.k.a, dependencies of dependencies. Those are true runtime dependencies too.

Got it. I will work on this feature in next PR.

**Review by kezhenxu94 — APPROVED** [review]

**Pull request merged**
