### PR TITLE
Support installing via go install

### PR DESCRIPTION
**Pull request by kezhenxu94**
For reviewers who want to try, please use `go install github.com/apache/skywalking-eyes/cmd/license-eye@goinstall`

### CODE REVIEW

**Review by wu-sheng — COMMENTED** [review]
A question, what goinstall could provide?

**Comment by kezhenxu94** [comment]
> A question, what goinstall could provide?

It's a more Go-native way to install Go tools, more convenient for demonstration, less steps (only one command) to quick start.

**Comment by kezhenxu94** [comment]
Consider it as the `brew` command in Go ecosystem.

**Comment by wu-sheng** [comment]
> Consider it as the `brew` command in Go ecosystem.

Love brew 😄

**Review by wu-sheng — APPROVED** [review]

**Pull request merged**
