### PR TITLE
Add support for MatLab files

### PR DESCRIPTION
**Pull request by kezhenxu94**

### CODE REVIEW

**Comment by wu-sheng** [comment]
Whoo, where is this from?

**Review by fgksgf — APPROVED** [review]

**Comment by kezhenxu94** [comment]
> Whoo, where is this from?

Voting for an incubator project (using Matlab) and want to add this to their codebase 😉

**Comment by wu-sheng** [comment]
> > Whoo, where is this from?
> 
> Voting for an incubator project (using Matlab) and want to add this to their codebase 😉

ASF incubator? Which project?

**Comment by kezhenxu94** [comment]
> > > Whoo, where is this from?
> > 
> > 
> > Voting for an incubator project (using Matlab) and want to add this to their codebase 😉
> 
> ASF incubator? Which project?

http://github.com/apache/incubator-mxnet

**Comment by wu-sheng** [comment]
> > > > Whoo, where is this from?
> > > 
> > > 
> > > Voting for an incubator project (using Matlab) and want to add this to their codebase 😉
> > 
> > 
> > ASF incubator? Which project?
> 
> [http://github.com/apache/incubator-mxnet](https://github.com/apache/incubator-mxnet)

Did they ping you directly? I didn't find the discussion or request on the mail list. or GitHub.

**Pull request merged**
