### PR TITLE
Add support for Smarty template language

### PR DESCRIPTION
**Pull request by emschu**

### CODE REVIEW

**Review by kezhenxu94 — COMMENTED** [review]
Thank you @emschu , can you also adjust pkg/license/norm.go file ?

**Comment by emschu** [comment]
@kezhenxu94 Thank you for your fast feedback. Yes, I can try to do this.

**Comment by emschu** [comment]
@kezhenxu94 I just changed `pkg/license/norm.go` in this PR and #39.

**Review by kezhenxu94 — APPROVED** [review]
> @kezhenxu94 I just changed `pkg/license/norm.go` in this PR and #39.

Thank you @emschu very much!

**Pull request merged**
